### ISSUE TITLE
Gnome 41 Support?

### ISSUE THREAD

**Issue by Scotty-Trees** [mzur/gnome-shell-always-indicator#10]
Greetings,

Gnome 41 was released this month and I was wondering if/when the extension will be updated? Thank you for your time and thank you for making an amazing extension I couldn't live without! Cheers

**Comment by mzur** [comment]
The official release is next week on September 22 :wink: I'll look into it when I have time. Meanwhile anyone wanting to help is welcome to do so.

**Comment by Scotty-Trees** [comment]
I am unfortunately not a coder at all myself, but hopefully someone out there may be able to assist you, otherwise feel free to tackle this issue when it is the most convenient for you, I have much patience so no worries :)

**Comment by mzur** [comment]
I checked the GNOME Shell 41 code and this extension should work fine with the new version. Please report back if you experience any issues.

**Comment by Scotty-Trees** [comment]
No worries, thanks very much for checking. I'm on EndeavourOS, so I expect to have Gnome 41 in the coming few weeks or less, so if I have any issues I'll let you know. Thanks for making a great extension btw.
