### ISSUE TITLE
[Feature Request] Add GNOME 44 Support

### ISSUE THREAD

**Issue by username0136** [mzur/gnome-shell-always-indicator#15]
Please add support for GNOME 44 to ensure compatibility with the latest version of GNOME and provide users with access to new features and improvements.

**Comment by username0136** [comment]
I disabled version validation and it seems to work fine, so I guess just need to add version in manifest.

**Comment by mzur** [comment]
Could you please send a pull request for this change? I'll test it once GNOME 44 becomes available in my Arch VM.

**Comment by username0136** [comment]
I can send the pull request as it is working completely fine on my end, but my knowledge of how GNOME extensions work is limited or nonexistent. Therefore, I am uncertain if adding the version to the manifest file will be sufficient. I apologize for any inconvenience, but I am not the right person for this task.

**Comment by mzur** [comment]
Adding the version may be enough. I'll test everything in the PR to make sure it works. It would be great if you still could send a PR 😉
