### ISSUE TITLE
Gnome 44 -> indicator._settings is undefined

### ISSUE THREAD

**Issue by Flavelius** [mzur/gnome-shell-always-indicator#17]
Hi,
i just installed this extension via the extension manager in ubuntu 23.04, but it refuses to load with this error:
`this.indicator._settings is undefined`
i tried looking up where it could have come from and found, on gitlab, the dateMenu.js where it seems to exist, so i'm not sure why this is happening. 
In the extension manager it says Version 11 for this extension, maybe it's too old, but i couldn't find any version info apart from this number to compare it against.

**Comment by mzur** [comment]
Hi, I tested the extension with GNOME 44 on Arch and Ubuntu 23.04 and I couldn't reproduce the error. Do you have other extensions installed which could cause a conflict?

Version 11 is the most recent one of this extension (v3.5 here on GitHub).

**Comment by Flavelius** [comment]
As for related extensions, i have 'Notification Counter' and 'Expandable Notifications' active as well. But even with these and all others deactivated the error is unfortunately still the same. The error, it says, occured while loading the extension.
Apart from that it's a freshly downloaded official copy (iso from the ubuntu website). It's running inside a vm, although i can't imagine this making a difference. Gnome Shell version 44, wayland.

Could it be that this maybe requires an additional extension or other system libraries to be installed?

**Comment by mzur** [comment]
> Could it be that this maybe requires an additional extension or other system libraries to be installed?

No. In my test, I also installed a fresh Ubuntu 23.04 in a VM and added this extension. Can you please show the full error message?

**Comment by Flavelius** [comment]
Okay, sorry to have bothered you ..after i installed a system update that popped up literally just now, it seems to have magically resolved itself. When i rebooted to take a screenshot of the error message it suddenly is no longer there. Thanks for trying to help and sorry for the unhelpful info, it's a mystery to me too what happened here.
