### ISSUE TITLE
Don't show the indicator while there is a notification on the screen

### ISSUE THREAD

**Issue by sojusnik** [mzur/gnome-shell-always-indicator#3]
It would make more sense to me, if the indicator would appear only when there are notifications in the notification center and not while there's a notification on the screen. I find the current behaviour redundant and misleading — there is no need for the indicator while a notification is on the screen, because the notification stands out enough. Additionally, I often think that there are other notifications in the notifications center and after clicking on the indicator I realize that it just indicated the present notification.

Any ideas how to accomplish this?

**Comment by mzur** [comment]
You could experiment with the [`source`](https://github.com/mzur/gnome-shell-always-indicator/blob/7160d5f4ea485189fb3eeba30b8c030a9760a79a/always-indicator%40martin.zurowietz.de/extension.js#L53) objects. I used the `count` property but there is also [`unseenCount`](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/19fc7c4d31df94d223302187c1de118d42a2be7f/js/ui/dateMenu.js#L478) which didn't work as I expected. Maybe there are other properties that can be used.

**Comment by sojusnik** [comment]
I don't have any coding experience, so it's up to you.

**Comment by mzur** [comment]
I'll close this then, as I am fine with the current behavior.
