### ISSUE TITLE
Request: Update for GNOME 3.36

### ISSUE THREAD

**Issue by Scotty-Trees** [mzur/gnome-shell-always-indicator#4]
GNOME 3.36 is going to be released March 11 and I like your extension very much and hope it can be updated to include support for GNOME 3.36. Keep up the great work!

**Comment by mzur** [comment]
Please have a look at #5. Do you know of any changes about the extension preferences? The preferences window doesn't show up and no error is displayed.

**Comment by Scotty-Trees** [comment]
I don't know about any extension preference changes myself, but I do know a lot of extensions this time around for 3.36 don't seem to "just work" with the latest GNOME version. I recently found your wonderful extension and was hoping it would work in 3.36 because I'm on Solus GNOME (rolling distro), so I'll be on 3.36 very soon in the future. So I can always test it out when that happens to give you any further feedback.

**Comment by mzur** [comment]
I tested the changes and submitted the new version to extensions.gnome.org. It will be available soon.
